site_name: USTC OSH 2022 课程主页
repo_name: OSH-2022/OSH-2022.github.io
repo_url: https://github.com/OSH-2022/OSH-2022.github.io
theme:
  name: 'material'
  language: 'zh'
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - mdx_truly_sane_lists
  - toc:
      permalink: true
extra_css:
  # Borrow CSS from Linux 101 still
  - 'https://101.ustclug.org/css/extra.css'
nav:
  - 首页: README.md
  - 实验零: lab0/README.md
  - 大作业: x/README.md
  - FAQ: faq/README.md
